### ISSUE TITLE
Push Settings not working

### ISSUE THREAD

**Issue by Veerlo** [ebonyfaye/EMA#1]
I just downloaded EMA everything seems working fine except i can'T push settings to my minions!

Pushing all and individual modules doesn't seem to work!

**Comment by ebonyfaye** [comment]
You need the add the character your pushing the settings to on the the characters you want to receive the settings on EG:

Main is blossom, you add bubbles, buttercup in the team on that char 

on bubbles you need to add blossom 
on buttercup you need to add blossom
