### ISSUE TITLE
/click EMAAssistMaster not working in macros

### ISSUE THREAD

**Issue by gbsnsgrckr** [ebonyfaye/ema#116]
Since 11.0 it seems that the /click EMAAssistMaster function is not working. It works fine if you simply type it but within a macro it does not.

**Comment by gbsnsgrckr** [comment]
Been seeing other people are having the issue as well that don't seem to be using EMA so this may not be a problem with the addon but instead the game. I just only use /click in the context of EMA so I wasn't sure how to test outside of EMA.

**Comment by ebonyfaye** [comment]
this is a blizzard problem and hopefully they fix nothing I can do about this I don't think
