### ISSUE TITLE
Latest update to WoW stopping EMA from working.

### ISSUE THREAD

**Issue by Hicks10uk** [ebonyfaye/ema#118]
Thank you for keeping this addon going!

Interface/addons/EMA/Modules/QuestWatcher.lua:1062 attempt to index field 'db' (a nil value)

Interface/AddOns/EMA/Core/Core.lua:42: attempt to call global 'GetAddOnMetadata' (a nil value)

**Comment by ebonyfaye** [comment]
Release-v4.7(0262) fixes
Interface/AddOns/EMA/Core/Core.lua:42: attempt to call global 'GetAddOnMetadata' (a nil value)

unsure about the questwachter stuff that more of a ACE3 prob if does not work after update it might be some other addon would need the full Lua Error to know what's wrong thanks!

**Comment by Hicks10uk** [comment]
v4.7 = working. Thank you!

I'll check everything that doesn't seem to be Ace3 as well, but I imagine it'll all be with that now.

**Comment by Hicks10uk** [comment]
Working ! Thank you!
