### ISSUE TITLE
Add option to copy macro

### ISSUE THREAD

**Issue by RobinFrcd** [ebonyfaye/ema#12]
Someone on curse had a great idea about adding an option to clone macro between toons.

https://www.curseforge.com/wow/addons/ema?comment=116

> One suggestion I have would be to add some ability to share or sync marcros with your alts. It's a big PITA to create the same macro multiple times. I've copied the global / character macro-cache.txt between accounts but that requires restarting the game. 

@ebonyfaye Do you want me to work on it ?

**Comment by RobinFrcd** [comment]
I've started to work on it, should look like this
![image](https://user-images.githubusercontent.com/29704178/97766971-68b8b580-1b19-11eb-82da-2670d5d48220.png)

Ok for you ?

**Comment by addonaddict** [comment]
I second this idea. I tend to copy paste the macro cache from game folder to do this but I would prefer to be able to sync macros of "teams" together. Cant wait!

**Comment by DejayRezme** [comment]
Oh thanks for picking up my suggestion from the curse comments :) 

I've found a workaround now with neuron. It's an actionbar replacement that allows to put macros (and keybinds) in each button and supports profiles. 
Here is an [example](https://i.imgur.com/Az4MyKU.jpg), I made a monstrously big 5 button action bar on my main and copied the neuron.lua from saved variables. 
If you edit the neuron.lua on your main and add ["<CharacterName> -<Server Name>"] = "<ProfileName", it copies over pretty automatically. 

I guess you could also do something similar to the sync item bar? Allow macros to be put there, allow the bar to be scaled and change padding to be more compact, lock the buttons to accidental drag (only shift). And allow it to only show on slaves maybe. That way you could configure a new spell for all your team and click them without the need for broadcasting.

Maybe a better solution would be some kind of feature that allows EMA to sync one neuron action bar. Or maybe the whole profile accross your team. Just sending the whole profile data might be easier but probably a bit much data (300kb for mine currently). I find neuron a bit fiddly but it's powerful. 

Just adding some suggestions and ideas, thanks so much for the addon!
