### ISSUE TITLE
Suggestion - character level on display board

### ISSUE THREAD

**Issue by ghost** [ebonyfaye/ema#15]
In the box that shows the character names, health and such, would it be possible to also put their level there as well?

**Comment by addonaddict** [comment]
i second this, i find myself switching windows all the time to do this quickly

**Comment by RobinFrcd** [comment]
Implemented in #19 (if you guys still multibox 👍)

![image](https://user-images.githubusercontent.com/29704178/98154184-b2681e00-1ed4-11eb-87b8-c681cb2146a0.png)
