### ISSUE TITLE
Questwatcher bug

### ISSUE THREAD

**Issue by Pharou80** [ebonyfaye/ema#2]
EMA\Modules\QuestWatcher.lua:2414: attempt to compare number with boolean
[string "@EMA\Modules\QuestWatcher.lua"]:2414: in function `DisplayAutoQuestPopUps'
[string "@EMA\Modules\QuestWatcher.lua"]:2145: in function `QuestWatcherQuestListScrollRefresh'
[string "@EMA\Modules\QuestWatcher.lua"]:1520: in function `UpdateQuestWatchList'
[string "@EMA\Modules\QuestWatcher.lua"]:1502: in function `DoQuestWatchObjectiveUpdate'
[string "@EMA\Modules\QuestWatcher.lua"]:2518: in function `EMAOnCommandReceived'
[string "@EMA\Core\Core.lua"]:444: in function `OnCommandReceived'
[string "@EMA\Core\Communications.lua"]:359: in function `?'

**Comment by ebonyfaye** [comment]
should be fixed in (build 0160)
