### ISSUE TITLE
Mount team when using pressing key instead of clicking or add macro command?

### ISSUE THREAD

**Issue by DejayRezme** [ebonyfaye/ema#20]
This would be a feature request, thanks for this great addon, now it's more useful than ever!

I noticed that my team only mounts up when I click a mount, but not when I press a hotkey on my main. Since input broadcasting is now banned it would be nice if mounting the team when pressing a hotkey on the master was possible too.

Or alternatively is there / could there be a command like "/ema-team mount" that I could put in a macro?

It would also be nice to have the team mount when using travel form, or use travel form instead of mounts if you're on druids. But I assume this is not possible in the api since it is a spell not a mount? But the above command would at least allow you to mount your team when the leader is a druid switching into flight form.

**Comment by DejayRezme** [comment]
Oh ok found the problem. I looked into the code and found a line "if IsShiftKeyDown() == false then" to block sending the mount up command. Coincidentally I have my mount keybind on Shift-X haha. This explains why it was not working for me but is probably not an issue for others. I guess I could:

* change keybinds (meh), 
* just patch my local code
* you could make in configurable
* or add a console command to mount the team 

Last option would be best for me, then I'd just put it in a macro for flightform. Maybe I can patch the code in myself, where would I add it? 

I'd still love to know if it's possible to cast flightform via addon. I figure it's probably not.

**Comment by ebonyfaye** [comment]
travel form is not a "mount" and there for you can not call it with summonMount() that ema calls, spells can not be called from addons they have to be a hardware event....

am sorry about your shift problem most would use alt/ctrl to mount  theats why its on shift its a bit to much work for me atm to allow the user to change that you could just edit the code and "--" the iskeydown and the --end for it.

as for you request to "mount" from a keybinding it would not know what mount to "use" useless i mapped to random mount and then you get all sort of problems with mounts that can not fly and i do not feel like getting around that that's a hole new level for now.

**Comment by DejayRezme** [comment]
Thanks for the reply. Yeah I figured about travel form.

And no worries I can patch it but just resorted to changing my hotkey (ouch muscle memory haha). After figuring it out I realize it's extremely low priority.

<Admin> Don't post rival name add-ons here.

**Comment by croana** [comment]
Hey, I also happen to have my mount macro bound to shift+= (and have had it there for over 10 years), so mounting up as a team is SUPER inconsistent for me. I just thought it was a world lag issue before seeing this ticket.

It would be really helpful if you made a mount macro as suggested by OP. Is there no way to simply make it call the same function you're already calling to mount up? Or is there really no way to remove the shift modifier from the code? I don't mind adding something like `/ema-team mount` to my mount up macro, but it does seem a bit inconvenient to have to change your code manually every time you update the addon.

As for what random mount to call....if that's the route you want to go, couldn't you just summon any random FLYING mount? Flying mounts work on the ground, too, so that shouldn't be an issue. The only place this would break is underwater, potentially, if the user has a macro to auto-choose an underwater mount.

I'm really sorry I can't help more. I don't code. But the addon "Livestock" seems to be able to differentiate between flying and nonflying mounts fine. Maybe that would help?

**Comment by croana** [comment]
Hm, I tried commenting out line 606 in Interaction.lua

`if IsShiftKeyDown() == false then`

But my characters still don't mount up together when shift is pressed. All that happened is the icon next to "Interaction" in the config panel disappeared. I think I did something wrong.

Sorry, what should I comment out for this to work properly all the time? Thanks. :)

**Comment by ebonyfaye** [comment]
U need to do the end as well.

**Comment by DejayRezme** [comment]
To answer the question about what mount to use, you could just use "C_MountJournal.SummonByID(0)" which calls a random appropriate favourite mount that you can set on each character. Which could be nice if you run with a diverse team that each have different favourite mounts set, so they look more individual. 

There is now a Summon Random Favorite Mount button at the top-right of your Mounts collection (default hotkey: Shift-P). This smart button selects randomly from among the mounts that you’ve marked as favorites, and chooses a mount that is suitable for your current zone and situation. There is a comment on wowhead here: https://www.wowhead.com/spell=150544/summon-random-favorite-mount#comments

Again, just a suggestion :)

@croana Yeah you need to put -- before the "if" but also before the "end" below this on the same indentation.

**Comment by ebonyfaye** [comment]
request added to v9.0.2-Release-v3.1(0180) 

have fun

**Comment by ebonyfaye** [comment]
ok changed this again

## Interaction
	--Undo the mount change in (0180)
	-- New Mount Option
		-New command: "/ema-interaction mount <Tag>" 
		- New KeyBinding, now calls "/ema-interaction mount all"
			- Will Now tell the team to summon a "Random Favorite Mount" (everyone summons there own random mount) 
				-- Dev note: This works with with shift!!!!!!!.
				-- You do not need to Have the settings ticked in the options to copy mount!
