### ISSUE TITLE
URL on CurseForge for posting errors is broken

### ISSUE THREAD

**Issue by fireymerlin** [ebonyfaye/ema#23]
When I click on the link in the description of the addon, I get:

**This repository does not have issue tracking enabled.**

**Comment by RobinFrcd** [comment]
Yep, everything is in this repo now. I agree with you, the link on curse should be updated.

**Comment by ebonyfaye** [comment]
AV updated that link 4 times it shows right in the admin gui

**Comment by RobinFrcd** [comment]
I think he's talking about the one in the description:
<img width="835" alt="image" src="https://user-images.githubusercontent.com/29704178/98860843-8f091a00-2464-11eb-835c-f8b3f4edf77c.png">

**Comment by ebonyfaye** [comment]
I updated there as well

**Comment by ebonyfaye** [comment]
ok should work now
