### ISSUE TITLE
[SUGGESTION] - Keybind for /assist {master}

### ISSUE THREAD

**Issue by fireymerlin** [ebonyfaye/ema#24]
Having a keybind to the assist the master would be very helpful.  Even it if couldn't be updated in combat, it would help.

**Comment by ebonyfaye** [comment]
Lol way to slow 🤣🤣 

See update

**Comment by DejayRezme** [comment]
-- Focus Master
-dev note: They will need to be pressed on every Character by "hand"/Window as well they will not update in combat.

Can an addon set the focus automatically, like follow? Or is that the reason why you have to press it by hand? I think if an addon could set focus you could implement things like old style healbot that just does everything for you.

I set it up so I switch to each member, target the master and press a macro with "/focus" on it. Then all combat abilities use focustarget. But the setup is a bit clumsy. At least with this setup I can theoretically recover if the master dies. Also you can /target [focustarget] and then press interact with target

**Comment by ebonyfaye** [comment]
No focus and target and assist are al locked down to blizzards own UI code
