### ISSUE TITLE
ItemUse.lua Usage: GetItemInfo(itemID

### ISSUE THREAD

**Issue by kittykatmax** [ebonyfaye/ema#25]
I've had this problem forever, and I've reported it before, but it's never been fixed.  I don't even USE the ItemUse feature, and have to suffer with it throwing literally _thousands_ of errors when **_disabled_**:

7688x EMA\Modules\ItemUse.lua:375: Usage: GetItemInfo(itemID|"name"|"itemlink")
[string "=[C]"]: in function `GetItemInfo'
[string "@EMA\Modules\ItemUse.lua"]:375: in function `UpdateQuestItemsInBar'
[string "@EMA\Modules\ItemUse.lua"]:1290: in function `?'
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

Would love to see a fix,  thank you.

**Comment by ebonyfaye** [comment]
somthing prob broke it even after you removed the item i would say go to your settings, and then use the clear all button and see what happens then report back if u still got a problem

**Comment by DejayRezme** [comment]
I probably just reported the same error #30

**Comment by ebonyfaye** [comment]
Again clear button in GUI will fix this issue
