### ISSUE TITLE
Reload Team, Logoff Team and Exit Team

### ISSUE THREAD

**Issue by Xatan** [ebonyfaye/ema#28]
heya Blossom, it would be great to be able to Reload the UI for all the Team, Logoff the Team or Exit the Team with one key press on the current character.
I think that Isboxer provided key bindings to do that. 
I imagine your EMA addon could also do that by sending-addon-to-addon messages to all players in the team. The addon commands would be executed as you do now by executing a macro to perform those actions as required. 
Key bindings for Reload, Reload Team, Logoff, Logoff Team, Exit and Exit Team would be required also.
Thanks in advance :)

**Comment by ebonyfaye** [comment]
/camp, /logout /exit etc all need a hardware event so you would have to go to them windows to press the key or whatever

Reloadui() as well needs a hardware event so again you can not boardcast this though the addon comms,

macros need a hardware event as well. 

sorry
