### ISSUE TITLE
DisplayTeam.lua:2983: attempt to index field 'db' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [ebonyfaye/ema#3]
527x EMA\Modules\DisplayTeam.lua:2983: attempt to index field 'db' (a nil value)
[string "@EMA\Modules\DisplayTeam.lua"]:2983: in function `SendPowerStatusUpdateCommand'
[string "@EMA\Modules\DisplayTeam.lua"]:2975: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by ebonyfaye** [comment]
t seems like your “db” ema.lua in wtf is broken, sis u do anything for this to happen?

**Comment by Thrumbar** [comment]
Appears to be a conflict with
chatcopypaste
https://www.curseforge.com/wow/addons/chat-copy-paste

Removing said addon stops all the db errors.
