### ISSUE TITLE
Error with item use bar

### ISSUE THREAD

**Issue by DejayRezme** [ebonyfaye/ema#30]
I get an error. I think it might have been that I dragged the smelting icon for the mining profession into it. These are 3 errors I've got and my item use bar can't be changed, cleared or synced. I've copied the relevant "itemsAdvanced" portion of the savedvariables at the end. I'll try deleting that section and see if that fixed it :)

---
Message: Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua:1660: IsAttackSpell(): Invalid spell slot
Time: Mon Nov 16 19:50:06 2020
Count: 1
Stack: Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua:1660: IsAttackSpell(): Invalid spell slot
[string "=[C]"]: in function `IsAttackSpell'
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:1660: in function `IsAttack'
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:1427: in function <Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua:1426>
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:1152: in function <Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua:1139>
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:1135: in function `UpdateAction'
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:459: in function `UpdateState'
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:441: in function `SetState'
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:410: in function `UpdateItemsInBar'
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:1166: in function <Interface\AddOns\EMA\Modules\ItemUse.lua:1154>
[string "=[C]"]: ?
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:498: in function `InitializeAddon'
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:623: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

---

Message: Interface\AddOns\EMA\Modules\ItemUse.lua:410: SetStateAction: unknown action type: companion
Time: Mon Nov 16 19:50:42 2020
Count: 1
Stack: Interface\AddOns\EMA\Modules\ItemUse.lua:410: SetStateAction: unknown action type: companion
[string "=[C]"]: ?
[string "@Interface\AddOns\EMA\Libs\EMALibActionButton-1.0.lua"]:419: in function `SetState'
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:410: in function `UpdateItemsInBar'
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:1183: in function <Interface\AddOns\EMA\Modules\ItemUse.lua:1171>
[string "=[C]"]: ?
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:70: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:527: in function `EnableAddon'
[string "@Interface\AddOns\ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua"]:630: in function <...ActionBarProfiles\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

Locals: <none>

---

Message: Interface\AddOns\EMA\Modules\ItemUse.lua:1393: attempt to index field 'sharedInvData' (a nil value)
Time: Mon Nov 16 20:08:54 2020
Count: 11
Stack: Interface\AddOns\EMA\Modules\ItemUse.lua:1393: attempt to index field 'sharedInvData' (a nil value)
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:1393: in function `ReceiveItemCount'
[string "@Interface\AddOns\EMA\Modules\ItemUse.lua"]:1457: in function `EMAOnCommandReceived'
[string "@Interface\AddOns\EMA\Core\Core.lua"]:444: in function `OnCommandReceived'
[string "@Interface\AddOns\EMA\Core\Communications.lua"]:359: in function `?'
[string "@Interface\AddOns\ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...les\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\ActionBarProfiles\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\EMA\Libs\AceComm-3.0\AceComm-3.0.lua"]:222: in function `OnReceiveMultipartLast'
[string "@Interface\AddOns\EMA\Libs\AceComm-3.0\AceComm-3.0.lua"]:256: in function <...nterface\AddOns\EMA\Libs\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>
---

			["itemsAdvanced"] = {
				{
					["action"] = 2656,
					["kind"] = "spell",
				}, -- [1]
				{
					["action"] = "item:173716",
					["kind"] = "item",
				}, -- [2]
				{
					["action"] = "item:172013",
					["kind"] = "item",
				}, -- [3]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [4]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [5]
				{
					["kind"] = "empty",
				}, -- [6]
				{
					["action"] = 18960,
					["kind"] = "spell",
				}, -- [7]
				{
					["action"] = "item:140192",
					["kind"] = "item",
				}, -- [8]
				{
					["action"] = "item:110560",
					["kind"] = "item",
				}, -- [9]
				{
					["action"] = "item:6948",
					["kind"] = "item",
				}, -- [10]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [11]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [12]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [13]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [14]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [15]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [16]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [17]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [18]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [19]
				{
					["action"] = "empty",
					["kind"] = "empty",
				}, -- [20]

**Comment by ebonyfaye** [comment]
You could just use the clar button in the GUI this wipes the db as well.

**Comment by DejayRezme** [comment]
I did that and that fixed it. Then the same error occurred again :) Not sure what causes it, maybe it was the druid "dreamwalk" spell. 

Now I cleared the DB, disabled show, disabled add quest item, disabled sync on all clients. So far the error has not returned.

**Comment by ebonyfaye** [comment]
can not get this to happen with any of the two spells u asked me to try

**Comment by DejayRezme** [comment]
Sorry I don't know exactly how to reproduce this.
