### ISSUE TITLE
Information.lua:141: attempt to index local 'info' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [ebonyfaye/ema#32]
7x EMA\Modules\Information.lua:141: attempt to index local 'info' (a nil value)
[string "@EMA\Modules\Information.lua"]:141: in function `CurrencyIconAndName'
[string "@EMA\Modules\Information.lua"]:1042: in function `CurrDropDownBox'
[string "@EMA\Modules\Information.lua"]:702: in function `SettingsRefresh'
[string "@EMA\Modules\Information.lua"]:952: in function <EMA\Modules\Information.lua:938>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by ebonyfaye** [comment]
this was a api change in the new patch as i play in the EU we did not have it till today

thanks for report and understanding

fixed in v9.0.2-Release-v3.1(0178)
