### ISSUE TITLE
Quest with one "gossip" option

### ISSUE THREAD

**Issue by SirRestraint** [ebonyfaye/ema#33]
Hello,

first of all, great addon and great work.

I have a question about auto-complete for quest.
Is there an option to auto-select/auto-complete quest with 1 gossip option?
If not, would be possible to add that as feature?
Before I swapped to EMA, I used QuickQuest addon which has that option.

Thank you
Restraint

**Comment by ebonyfaye** [comment]
it can already do this, if you have auto quests on

or it should clone if u click with someone in the team (make sure your
updated as there is a lot of api changes on this and i keep finding bugs
with some npc guys)

**Comment by SirRestraint** [comment]
I can share my settings, but it didn't work for single quest.

Scenario:
Open quest dialog on all toons and click the line to proceed in quest, only that "clicking" toon will proceed.
- I use mirror selections from master
- it works for Complete quest if the quest is just simple turn in
- it not works if you have to click "talking line" to first proceed in quest and than Complete it

Example is quest chain for legendary cloak now in BFA when you have to ask Magni to tell you what he discovered to get the Complete status and than turn in quest.
https://www.wowhead.com/quest=57222/investigating-the-halls
