### ISSUE TITLE
Team dismounts together despite config to the contrary

### ISSUE THREAD

**Issue by chckxy** [ebonyfaye/ema#35]
Configuration:
- `Mount With Team` is checked
- `Dismount With Team` is unchecked

What I expect:
- When the master mounts, the minions mount
- When the master dismounts, the minions stay mounted

What actually happens:
- When the master mounts, the minions mount (right)
- When the master dismounts, the minions also dismount (wrong)

I've locally fixed this by commenting out https://github.com/ebonyfaye/ema/blob/f750783de6c8fc1102006991ca065ed3a75f3f54/Modules/Interaction.lua#L675 but I'm not sure if this is the right general solution

**Comment by ebonyfaye** [comment]
If your using the new mount keybinding then it is a mount up and dismount toggle no way to track what or who mounted if anything.

**Comment by chckxy** [comment]
I'm not using an EMA keybinding, this is just e.g. casting a mount from an action bar.  Seems to work perfectly for my use case except the undesired dismounting.

**Comment by kittykatmax** [comment]
This is still a problem.  I have "dismount with team" disabled on everyone, and randomly, everyone dismounts if one dismounts.  Even if they aren't in party.  Even if they're in different expansion zones!  I can live with the inability to use passenger mounts, but it's a huge inconvenience, but my characters are being murdered. :(  

Perhaps remove the functionality if you don't want to have to troubleshoot it?  In the meantime, I'll be trying the "fix" above.  Thank you for this addon!!

**Comment by ebonyfaye** [comment]
fixed
