### ISSUE TITLE
Send /setview via addon communications

### ISSUE THREAD

**Issue by croana** [ebonyfaye/ema#36]
According to FireyMerlin in the wow channel in the ISBoxer discord, they were able to send a /setview macro to all characters at once using addon messaging. Is it actually possible to add a (or multiple) setview /click, or /ema macro that would work on all slave toons at once?

![image](https://user-images.githubusercontent.com/28045827/100004709-cb6f3b00-2dbf-11eb-84f9-47b6284f1357.png)

**Comment by DejayRezme** [comment]
My guess is this isn't done in a macro, the API is just unprotected and allows addons to do this:

https://wowwiki.fandom.com/wiki/API_SetView
