### ISSUE TITLE
New error after moving Heart of Azeroth to bank

### ISSUE THREAD

**Issue by TheRealMaxion** [ebonyfaye/ema#39]
Got this error after teleporting to a new area (which I guess makes stuff load again) after putting my Heart of Azeroth in the bank:

Message: Interface\AddOns\EMA\Modules\DisplayTeam.lua:2485: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))

**Comment by ebonyfaye** [comment]
u tried unticking  Azerite in the gui? there little i can do with curse
problems atm

**Comment by TheRealMaxion** [comment]
It was not ticked. No worries about getting the fix out fast, just letting you know about it. :)
