### ISSUE TITLE
QuestWatcher.lua:1056: attempt to index field 'db' (a nil value)

### ISSUE THREAD

**Issue by Thrumbar** [ebonyfaye/ema#4]
271x EMA\Modules\QuestWatcher.lua:1056: attempt to index field 'db' (a nil value)
[string "@EMA\Modules\QuestWatcher.lua"]:1056: in function `?'
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ore\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@DataStore\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@DataStore\libs\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <DataStore\libs\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by ebonyfaye** [comment]
Duplicate of #3
