### ISSUE TITLE
"Follow" and maybe other commands not working on Realm with "-" , such as Azjol-Nerub

### ISSUE THREAD

**Issue by burruz** [ebonyfaye/ema#44]
I have been troubleshooting a new setup on the Azjol Nerub Server, whenever I try and use the Follow command via Alt-F it just comes up on the slave window as "Unknown Unit". I wanted to double-check to make sure it wasnt additional addons, key binds or anything getting in the way, So I recreated exactly the same team on Outland and it works the first time without any issues. 

I cut out as much hassle as possible and just made a team with two characters, no other addons and default keybinds. 

thank you

**Comment by ebonyfaye** [comment]
ya i think i had problems with this realm and the "unit" api before :(
