### ISSUE TITLE
Possible Quest bug with auto completing quests

### ISSUE THREAD

**Issue by Voraga** [ebonyfaye/ema#5]
When I take a quest like the choose a foothold quest and select my foothold it doesn't autocomplete the choose foothold so I can continue (see link to screen shot) instead I have to open my quest log and press complete. In fact it seem any quest of this type, (ones that the blizzard UI auto completes) gets stuck at turn in and I have to do it through the log.

https://tinyurl.com/y4ugpzdu

**Comment by ebonyfaye** [comment]
duplicate #2
