### ISSUE TITLE
Persistent error on interacting with repairer NPC

### ISSUE THREAD

**Issue by Nerillida** [ebonyfaye/ema#50]
Using Release-v4.0(0200)

WoW 2.5.1 TBC Classic

Message: Interface\AddOns\EMA\Modules\Toon.lua:1504: attempt to call global 'CanGuildBankRepair' (a nil value)
Time: Mon Aug 23 12:31:48 2021
Count: 1
Stack: Interface\AddOns\EMA\Modules\Toon.lua:1504: attempt to call global 'CanGuildBankRepair' (a nil value)
[string "=(tail call)"]: ?
[string "@Interface\AddOns\EMA\Modules\Toon.lua"]:1504: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\EMA\Libs\AceEvent-3.0\AceEvent-3.0.lua"]:120: in function <...erface\AddOns\EMA\Libs\AceEvent-3.0\AceEvent-3.0.lua:119>

Locals: <none>

It does not seem to affect anything else in EMA.
May be that guild bank repairs are not (yt) in tbc.

**Comment by ebonyfaye** [comment]
fixed in 201

Yes i kinda jumped the gun on this one (was using ptr ;) )
