### ISSUE TITLE
Clicking Request Stop Button while flying

### ISSUE THREAD

**Issue by Nerillida** [ebonyfaye/ema#51]
Using Release-v4.0(0200)

WoW 2.5.1 TBC Classic

Message: Interface\AddOns\EMA\Modules\Interaction.lua:598: attempt to call global 'CanExitVehicle' (a nil value)
Time: Tue Aug 24 23:17:22 2021
Count: 2
Stack: Interface\AddOns\EMA\Modules\Interaction.lua:598: attempt to call global 'CanExitVehicle' (a nil value)
[string "@Interface\AddOns\EMA\Modules\Interaction.lua"]:598: in function <Interface\AddOns\EMA\Modules\Interaction.lua:594>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `TaxiRequestEarlyLanding'
[string "@Interface\FrameXML\MainMenuBar.lua"]:295: in function <Interface\FrameXML\MainMenuBar.lua:293>

Locals: sender = <table> {
 moduleDisplayName = "Interaction"
 modules = <table> {
 }
 SettingsToggleTellBoEEpic = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:446
 SettingsSetMessageArea = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:390
 SecureHook = <function> defined @Interface\AddOns\EMA\Libs\AceHook-3.0\AceHook-3.0.lua:336
 settingsDatabaseName = "InteractionProfileDB"
 TeamMount = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:711
 EMAOnSettingsReceived = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:457
 SetDefaultModulePrototype = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 LeavsTaxi = false
 IsEnabled = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 SettingsToggleDisMountWithTeam = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:421
 ScheduleTimer = <function> defined @Interface\AddOns\EMA\Libs\AceTimer-3.0\AceTimer-3.0.lua:94
 SettingsToggleTakeTaxi = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:400
 AmNotMounted = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:775
 EMARegisterModule = <function> defined @Interface\AddOns\EMA\Core\Module.lua:57
 EMAChatCommand = <function> defined @Interface\AddOns\EMA\Core\Module.lua:109
 RegisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SettingsCreateTaxi = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:222
 hooks = <table> {
 }
 db = <table> {
 }
 ReceiveRandomMountWithTeam = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:789
 SetEnabledState = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @Interface\AddOns\EMA\Libs\AceHook-3.0\AceHook-3.0.lua:274
 SettingsToggleMountInRange = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:431
 SettingsTogglerequestStop = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:405
 TaxiRequestEarlyLanding = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:594
 OnEnable = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:175
 TakeTaxiNode = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:570
 SettingsChangeTaxiTimer = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:410
 OnInitialize = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:150
 NewModule = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EMASendSettings = <function> defined @Interface\AddOns\EMA\Core\Module.lua:66
 COMMAND_CLOSE_TAXI = "EMACloseTaxi"
 TAXIMAP_OPENED = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:512
 GetName = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 EMASendCommandToTeam = <function> defined @Interface\AddOns\EMA\Core\Module.lua:71
 name = "Interaction"
 SettingsPushSettingsClick = <function> defined @Interface\AddOns\EMA\Modules\Interaction.lua:218
 settingsFrame = <unnamed> {
 }
 Disable = <function> defined @Interface\AddOns\Atlas\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetConfiguration = <function> defined @Interface\AddOns

**Comment by ebonyfaye** [comment]
fixed in next release.
