### ISSUE TITLE
"Push Settings" does not work correctly

### ISSUE THREAD

**Issue by finegorko** [ebonyfaye/ema#52]

**Comment by ebonyfaye** [comment]
this is not helpful is this tbc? classic or retail push all settings some settings?

**Comment by finegorko** [comment]
is this retail,
for example Mailing, I click Push Settings and nothing happens, the settings are not transferred.
and if you click 'Push All Settings' then it selectively transfers the settings

**Comment by finegorko** [comment]
And the quests that I receive from mobs after receiving them does not disappear the inscription "Quest Discovered" "Click to accept the quest", I have to reload the interface several times so that this inscription disappears and does not interfere

**Comment by ebonyfaye** [comment]
Test this on Settings on Build 202

Quest is Nothing to do with this,

Note: i only got one game account subbed to wow i can not test everything on demo/ptr.

+ i was going to come back not really have as of yet :(

so u have to help me out and see if that fixes it for 9.1

**Comment by finegorko** [comment]
"Push All Settings" works correctly if the "Enable Guild Communication" function is enabled.
