### ISSUE TITLE
 attempt to call method 'SetBackdrop' (a nil value) WoW 9.1

### ISSUE THREAD

**Issue by Thrumbar** [ebonyfaye/ema#53]
1x EMA\Modules\QuestWatcher.lua:552: attempt to call method 'SetBackdrop' (a nil value)
[string "@EMA\Modules\QuestWatcher.lua"]:552: in function `CreateQuestWatcherFrame'
[string "@EMA\Modules\QuestWatcher.lua"]:168: in function <EMA\Modules\QuestWatcher.lua:156>
[string "=[C]"]: ?
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:70: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:65>
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:498: in function `InitializeAddon'
[string "@DataStore\libs\AceAddon-3.0\AceAddon-3.0-13.lua"]:623: in function <DataStore\libs\AceAddon-3.0\AceAddon-3.0.lua:615>

**Comment by ebonyfaye** [comment]
fixed in Build (201)
