### ISSUE TITLE
[Retail] Mount/Dismount with team not triggered

### ISSUE THREAD

**Issue by KegDwarf** [ebonyfaye/ema#55]
Version:Release-v4.0(0201)

The team is 3 characters, options are synced

Mount option checked : 
Mount with team
Dismount with team

Mount option not checked:
Only dismount with master

When i reload on one character, it seems to notice that i am mounted, and when i dismount the command is sent to the 2 others characters. But then, mounting / dismount trigger nothing.

I have most likely narrow it down to the function EMA:OnEnable() in interation.lua
You may have forgotten the parenthesis in EMAPrivate.Core.isEmaClassicBccBuild
if EMAPrivate.Core.isEmaClassicBccBuild == false then
		EMA:RegisterEvent( "UNIT_SPELLCAST_START" )
		EMA:RegisterEvent( "UNIT_SPELLCAST_SUCCEEDED" )
	end

if i change it to 
if EMAPrivate.Core.isEmaClassicBccBuild() == false then
		EMA:RegisterEvent( "UNIT_SPELLCAST_START" )
		EMA:RegisterEvent( "UNIT_SPELLCAST_SUCCEEDED" )
	end
it seems to work

Hope this help you, thanks for your work

**Comment by fireymerlin** [comment]
Mount with team does not work for me.

**Comment by fireymerlin** [comment]
I made the changes suggested by KegDwarf  on Aug 31 and that fixed the issue for me.

**Comment by ebonyfaye** [comment]
issue#63
