### ISSUE TITLE
Request: Some Options saved account wide?

### ISSUE THREAD

**Issue by Voraga** [ebonyfaye/ema#6]
I'm not sure how difficult this would be, but I find that with every new character/team that I have to relocate the EMA Team and the Sync/Clear Item boxes. Is there any (hopefully easy) way to include these two item's locations as an account wide variable?

A few others that might be helpful:
Default Message, Vendor/Repair check boxes, things of this nature that you want consistent over all groups.

Thanks so much for all your hard work,
Voraga

**Comment by ebonyfaye** [comment]
Would be a pain there is profiles you can "copy" from a other team that kinda does what your after.

**Comment by Jabberie** [comment]
Use "Copy From" your main team and then fix your Team List. Then push all. :)
