### ISSUE TITLE
Minor formatting issue 

### ISSUE THREAD

**Issue by DiscordGregory** [ebonyfaye/ema#60]
On lines 1490 and 1500 of QuestWatcher.lua I believe there is a space missing after the colon
`local EditedQuestName = tostring("Bonus:")..(info.title)`
![image](https://user-images.githubusercontent.com/59945495/140686681-a4b5067c-3ebf-457e-940d-a717ad8a72f7.png)

Not sure if there should be one between Progress and Bar as well in the image above or if that's intentional

**Comment by ebonyfaye** [comment]
added space
