### ISSUE TITLE
[Bug] Trying to stop a flight early clicking leave taxi button

### ISSUE THREAD

**Issue by DiscordGregory** [ebonyfaye/ema#61]
I wasn't multiboxxing at the time, only playing one character not in a party at all if that helps.

1x EMA\Modules\Interaction.lua:601: attempt to perform arithmetic on field 'COMMA' (a nil value)
[string "@EMA\Modules\Interaction.lua"]:601: in function <EMA\Modules\Interaction.lua:594>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `TaxiRequestEarlyLanding'
[string "@Zymux\Modules\Bars\vehicle.lua"]:21: in function <Zymux\Modules\Bars\vehicle.lua:19>

Locals:
sender = <table> {
 moduleDisplayName = "Interaction"
 modules = <table> {
 }
 SettingsToggleTellBoEEpic = <function> defined @EMA\Modules\Interaction.lua:446
 SettingsSetMessageArea = <function> defined @EMA\Modules\Interaction.lua:390
 SecureHook = <function> defined @ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:336
 settingsDatabaseName = "InteractionProfileDB"
 TeamMount = <function> defined @EMA\Modules\Interaction.lua:711
 EMAOnSettingsReceived = <function> defined @EMA\Modules\Interaction.lua:457
 SetDefaultModulePrototype = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:409
 LeavsTaxi = false
 IsEnabled = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:451
 SettingsToggleDisMountWithTeam = <function> defined @EMA\Modules\Interaction.lua:421
 ScheduleTimer = <function> defined @ArkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:94
 SettingsToggleTakeTaxi = <function> defined @EMA\Modules\Interaction.lua:400
 AmNotMounted = <function> defined @EMA\Modules\Interaction.lua:775
 EMARegisterModule = <function> defined @EMA\Core\Module.lua:57
 EMAChatCommand = <function> defined @EMA\Core\Module.lua:109
 RegisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @TomTom\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 SettingsCreateTaxi = <function> defined @EMA\Modules\Interaction.lua:222
 hooks = <table> {
 }
 db = <table> {
 }
 ReceiveRandomMountWithTeam = <function> defined @EMA\Modules\Interaction.lua:789
 SetEnabledState = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:424
 Hook = <function> defined @ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:274
 SettingsToggleMountInRange = <function> defined @EMA\Modules\Interaction.lua:431
 SettingsTogglerequestStop = <function> defined @EMA\Modules\Interaction.lua:405
 TaxiRequestEarlyLanding = <function> defined @EMA\Modules\Interaction.lua:594
 OnEnable = <function> defined @EMA\Modules\Interaction.lua:175
 TakeTaxiNode = <function> defined @EMA\Modules\Interaction.lua:570
 SettingsChangeTaxiTimer = <function> defined @EMA\Modules\Interaction.lua:410
 OnInitialize = <function> defined @EMA\Modules\Interaction.lua:150
 NewModule = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:235
 EMASendSettings = <function> defined @EMA\Core\Module.lua:66
 COMMAND_CLOSE_TAXI = "EMACloseTaxi"
 TAXIMAP_OPENED = <function> defined @EMA\Modules\Interaction.lua:512
 GetName = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:279
 EMASendCommandToTeam = <function> defined @EMA\Core\Module.lua:71
 name = "Interaction"
 SettingsPushSettingsClick = <function> defined @EMA\Modules\Interaction.lua:218
 settingsFrame = <unnamed> {
 }
 Disable = <function> defined @!KalielsTracker\Libs\AceAddon-3.0\AceAddon-3.0.lua:314
 GetConfiguration = <function> defined @EMA\Modules\Interaction.lua:85
 Unhook = <function> defined @ArkInventory\Externals\Ace3\AceHook\AceHook-3.0.lua:418
 Print = <function> defined @ArkInventory\Externals\Ace3\AceConsole\AceConsole-3.0.lua:54
 OnMessageAreasChanged = <function> defined @EMA\Modules\Interaction.lua:385
 COMMAND_MOUNT_DISMOUNT = "EMAMountDisMount"
 TakesTaxi = false
 EnableAutoLoot = <function> defined @EMA\Modules\Interaction.lua:860
 UPDATE_BINDINGS = <function> defined @EMA\Modules\Interaction.lua:97

**Comment by ebonyfaye** [comment]
fixed
