### ISSUE TITLE
Team not mounting

### ISSUE THREAD

**Issue by Pyrx666** [ebonyfaye/ema#63]
Team not mounting with either update 0204 or 0205. Still able to mount as team if i'm using 0203. This is on life Shadowlands content.. TY again for all your hard work

**Comment by Thrumbar** [comment]
The issue is caused by changes in interaction.lua where some lines changed true to false.   Changed them back and mount with team works in so far as I have tested.  Still testing this...

**Comment by fireymerlin** [comment]
For retail, mount with team and dismount is not working.

I edited the Interaction.lua file and commented out or removed all code related checks for "classic" and that fixed the problem.

I suspect the check for classic is not working.

**Comment by ebonyfaye** [comment]
am so sorry for the wait sent out a fix today
