### ISSUE TITLE
Repo doesn't include '.zip' for WowUp use.

### ISSUE THREAD

**Issue by jodysaliba** [ebonyfaye/ema#67]
The repo doesn't have a zip file to use with WowUp's auto updates. I believe another option is to have the addon listed on Wago.io.

![image](https://user-images.githubusercontent.com/1418509/168935416-f34f905b-060a-4680-b2e2-eb850913c1df.png)

**Comment by ebonyfaye** [comment]
i get very little for working on this very big addon and curseforge pays me for downloads even though it is £23 a year!
