### ISSUE TITLE
Ace3 related error

### ISSUE THREAD

**Issue by nancikennedy** [ebonyfaye/ema#68]
101x ...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua:30: script ran too long
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:30: in function <...Ons\Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Ace3\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `SendMessage'
[string "@EMA\Core\Team-Team.lua"]:869: in function <EMA\Core\Team.lua:811>
[string "@EMA\Core\Team-Team.lua"]:894: in function `AddPartyMembers'
[string "@EMA\Core\Team-Team.lua"]:1932: in function <EMA\Core\Team.lua:1931>
[string "=[C]"]: ?
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:72: in function <Ace3\AceGUI-3.0\AceGUI-3.0.lua:70>
[string "@Ace3\AceGUI-3.0\AceGUI-3.0-41.lua"]:306: in function `Fire'
[string "@Ace3\AceGUI-3.0-41\widgets\AceGUIWidget-Icon.lua"]:26: in function <Ace3\AceGUI-3.0\widgets\AceGUIWidget-Icon.lua:25>

**Comment by ebonyfaye** [comment]
same as #64
