### ISSUE TITLE
Sync issues forcing a /reload

### ISSUE THREAD

**Issue by addonaddict** [ebonyfaye/ema#7]
Hello, love the addon, been using for the longest time now.

There is an issue where the SYNC button does not sync properly until I /reload all windows and try again. Sometimes even twice in a row. Seems to be hit and miss, but most of the time 1 reload does the job.
This happens on a fresh PC without any addons. Just ISboxer running. Also happens regardless if i have option to sync with isboxer or not.

When this works, I can see the chat window get spammed with EMA messages like "sending settings for: xxxx". When it doesnt work, all I see on other windows is 2 lines of text saying "settings received from X character"

It seems to happen more often the more changes you make.
Also I do not spam the sync button, just click once and wait for results.

Thank you

**Comment by ebonyfaye** [comment]
So I know you mean push all settings?


I have not changed anything that you oils do this all mosty quest changes
updateing the API.

**Comment by addonaddict** [comment]
Correct I mean push all settings
I noticed this happening even before the prepatch
After prepatch hit i reset my PC and re-installed all addons fresh, with EMA running alone without any other addons, this still happens forcing a /reload
