### ISSUE TITLE
Followstrobe WOTLK?

### ISSUE THREAD

**Issue by deus81** [ebonyfaye/ema#72]
1) Has Blizzard disabled the followstrobe loop on WOTLK?!? O.o

2) Leave party has an arror

Message: Interface\AddOns\EMA\Core\Team.lua:1393: attempt to call field 'LeaveParty' (a nil value)
Time: Mon Sep 12 10:30:32 2022
Count: 3
Stack: Interface\AddOns\EMA\Core\Team.lua:1393: attempt to call field 'LeaveParty' (a nil value)
[string "@Interface\AddOns\EMA\Core\Team.lua"]:1393: in function <Interface\AddOns\EMA\Core\Team.lua:1388>
[string "@Interface\AddOns\EMA\Core\Team.lua"]:2162: in function `EMAOnCommandReceived'
[string "@Interface\AddOns\EMA\Core\Core.lua"]:460: in function `OnCommandReceived'
[string "@Interface\AddOns\EMA\Core\Communications.lua"]:385: in function `?'
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:119: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:29: in function <...las\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\Atlas\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua"]:64: in function `Fire'
[string "@Interface\AddOns\EMA\Libs\AceComm-3.0\AceComm-3.0.lua"]:264: in function <...nterface\AddOns\EMA\Libs\AceComm-3.0\AceComm-3.0.lua:246>

Locals: <none>

**Comment by ebonyfaye** [comment]
Has Blizzard disabled the followstrobe loop on WOTLK?!? Yes add-ons can nolonger call FollowUnit() and require a hardware event ( key press )

**Comment by ebonyfaye** [comment]
Thanks I'll look into it

**Comment by deus81** [comment]
They make the condition worse and worse for those who still try to play more than 1 account. Im only playing because i have still playtime left on 4 accounts. I wont buy dragonflight. Seems to be the same shit as always :D. Im trying to play wrath with 4 accounts and leveling a little bit on retail (mouse over and activating window, i wont risk wow open box because of the "mainstreaming" which can mean anything, even addons -.-, although wow open box is ony switching windows on keyUp). Thats it. Blizzard wont get a cent from me anymore for their deceitfil crap and how they treat women there!

Do you still stream or even play?

**Comment by ebonyfaye** [comment]
I do still play retail
