### ISSUE TITLE
Automatic quest sharing not working

### ISSUE THREAD

**Issue by RobinFrcd** [ebonyfaye/ema#8]
Interface\AddOns\EMA\Modules\Quest.lua:1589: attempt to call global 'GetNumFriends' (a nil value) 
[string "@Interface\AddOns\EMA\Modules\Quest.lua"]:1589: in function `CanAutoAcceptSharedQuestFromPlayer'
[string "@Interface\AddOns\EMA\Modules\Quest.lua"]:1623: in function `?'
[string "@Interface\AddOns\CopyPasta2\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:119: in function <...ta2\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:119>
[string "=[C]"]: ?
[string "@Interface\AddOns\CopyPasta2\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:29: in function <...ta2\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:25>
[string "@Interface\AddOns\CopyPasta2\libs\CallbackHandler-1.0\CallbackHandler-1.0-7.lua"]:64: in function `Fire'
[string "@Interface\AddOns\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0-4.lua"]:120: in function <...s\ElvUI\Libraries\Ace3\AceEvent-3.0\AceEvent-3.0.lua:119>

**Comment by ebonyfaye** [comment]
fixed

v9.0.1-Release-v3.0(0163)
