### ISSUE TITLE
Bug: GetContainerNumSLots error

### ISSUE THREAD

**Issue by nancikennedy** [ebonyfaye/ema#85]
On Retail, with v4.3(0225) installed. I am getting the following error. It started when I was doing the Primal Event daily and is now popping up every time I loot the essences, the items for the PE daily and on quest acceptance.

4x EMA/Modules/ItemUse.lua:629: attempt to call global 'GetContainerNumSlots' (a nil value)
[string "@EMA/Modules/ItemUse.lua"]:629: in function `IsInInventory'
[string "@EMA/Modules/ItemUse.lua"]:379: in function `UpdateQuestItemsInBar'
[string "@EMA/Modules/ItemUse.lua"]:1315: in function `?'
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:114: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:114>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:24: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:20>
[string "@Ace3/CallbackHandler-1.0-7/CallbackHandler-1.0.lua"]:59: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

**Comment by ebonyfaye** [comment]
Fixed
