### ISSUE TITLE
wotlk classic 3.4.1 api changes

### ISSUE THREAD

**Issue by bpkdasbaum** [ebonyfaye/ema#88]
wotlk classic 3.4.1 broke the addon due to API updates: [https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes](https://www.curseforge.com/linkout?remoteUrl=https://wowpedia.fandom.com/wiki/Patch_3.4.1/API_changes)

`Message: Interface/AddOns/EMA/Modules/Quest-Classic.lua:254: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
Time: Wed Jan 18 15:25:09 2023
Count: 1
Stack: Interface/AddOns/EMA/Modules/Quest-Classic.lua:254: Usage: SecureHook([object], method, [handler]): Attempting to hook a non existing target
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/BigDebuffs/Libs/AceHook-3.0/AceHook-3.0.lua"]:210: in function <...e/AddOns/BigDebuffs/Libs/AceHook-3.0/AceHook-3.0.lua:118>
[string "@Interface/AddOns/BigDebuffs/Libs/AceHook-3.0/AceHook-3.0.lua"]:340: in function `SecureHook'
[string "@Interface/AddOns/EMA/Modules/Quest-Classic.lua"]:254: in function <Interface/AddOns/EMA/Modules/Quest-Classic.lua:239>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...AddOns/BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...AddOns/BigDebuffs/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>

Locals: <none>`

`Message: .../AddOns/EMA/Libs/LibBagUtils-1.0/LibBagUtils-1.0.lua:356: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
Time: Wed Jan 18 15:25:10 2023
Count: 1
Stack: .../AddOns/EMA/Libs/LibBagUtils-1.0/LibBagUtils-1.0.lua:356: attempt to call upvalue 'GetContainerNumFreeSlots' (a nil value)
[string "=[tsm error check]"]:1: in main chunk
[string "=(tail call)"]: ?
[string "=[C]"]: ?
[string "@Interface/AddOns/EMA/Libs/LibBagUtils-1.0/LibBagUtils-1.0.lua"]:356: in function `CountSlots'
[string "@Interface/AddOns/EMA/Modules/Toon.lua"]:2020: in function `?'
[string "@Interface/AddOns/BigDebuffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/BigDebuffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/BigDebuffs/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/BigDebuffs/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...AddOns/BigDebuffs/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: `

**Comment by ebonyfaye** [comment]
fixed in Release-v4.3(0231)
