### ISSUE TITLE
Account "Not Linked"

### ISSUE THREAD

**Issue by hellgaet1337** [ebonyfaye/ema#92]
Hello
/ema config
Team
All my accounts from different server, and from yesterday they "Not linked"
Blizzard fix some API or what is that?

**Comment by hellgaet1337** [comment]
Im playing on Retail.

**Comment by ebonyfaye** [comment]
sorry i forgot to replay to this one had the flu 

anyway that means the realms are not connected so not everything can work this is a blizzard problem as u can not send addon commands to other realms that are not connected or "linked" unless your in the group or raid

sorry it was done for a help docs i nerver got around to doing a lot of work just keeping the addon work then make docs about everything

**Comment by hellgaet1337** [comment]
> sorry i forgot to replay to this one had the flu
> 
> anyway that means the realms are not connected so not everything can work this is a blizzard problem as u can not send addon commands to other realms that are not connected or "linked" unless your in the group or raid
> 
> sorry it was done for a help docs i nerver got around to doing a lot of work just keeping the addon work then make docs about everything

Hello, thank you for replay.
Also it was not main problem, but after 2 days everything start working fine, i think it's just some Blizzard lags.
